---
strategy: static
no_screen_padding: 'yes'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: 
id: 210390
name: Ghibli Backgrounds
refresh_interval: 15
